name: Update File from URL

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update-file:
    runs-on: ubuntu-latest
    env:
      FILE_URL: 'https://thewrightmatt.github.io/silver-spork/sample.json' # Replace with your JSON file URL
      FILE_PATH: './big_file.yaml'              # Replace with your YAML file path in the repo

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download JSON File from URL
        run: |
          curl -sSL "$FILE_URL" -o downloaded_file.json

      - name: Install yq (YAML Processor)
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      # Split the file into parts at '---'
      - name: Split YAML file
        run: |
          csplit --elide-empty-files --quiet --prefix=split_file "$FILE_PATH" "/^---$/" "{*}"
          mv split_file00 part1.yaml
          mv split_file01 part2.yaml
          echo "Split files created:"
          ls -l part*.yaml

      - name: Convert JSON to YAML
        run: |
          yq eval -Poy downloaded_file.json > downloaded_file.yaml

      - name: Print contents of file
        run: |
          pwd
          cat "$FILE_PATH"
          echo "************************************"
          echo "************************************"
          cat downloaded_file.yaml

      - name: Compare Files
        id: compare
        run: |
          if ! cmp -s downloaded_file.yaml part2.yaml; then
            echo "files_different=true" >> $GITHUB_OUTPUT
          else
            echo "files_different=false" >> $GITHUB_OUTPUT
          fi

      - name: Debug Output
        run: |
          echo "files_different is: ${{ steps.compare.outputs.files_different }}"
          echo "GITHUB_OUTPUT path is: $GITHUB_OUTPUT" #testing

      - name: Update File in Repository
        if: steps.compare.outputs.files_different == 'true'
        run: |
          cp downloaded_file.yaml part2.yaml

      # Combine the parts back together
      - name: Combine YAML files
        run: |
          cat part1.yaml > combined.yaml
          echo "---" >> combined.yaml
          cat part2.yaml >> combined.yaml
          mv combined.yaml big_file.yaml

      - name: Create Pull Request
        if: steps.compare.outputs.files_different == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: file-update
          title: Update file from URL
          commit-message: Update file from URL
          body: Change detected, trying update
          add-paths: |
            '$FILE_PATH'
